from selenium import webdriver
driver = webdriver.Firefox()
driver.get('https://www.yunke.com/index.main.login')
driver.find_element_by_xpath('/html/body/div[1]/div/section/div[2]/ul[2]/li[1]/form/div[1]/div[2]/input').clear()
driver.find_element_by_xpath('/html/body/div[1]/div/section/div[2]/ul[2]/li[1]/form/div[1]/div[2]/input').send_keys('17600117243')
driver.find_element_by_xpath('/html/body/div[1]/div/section/div[2]/ul[2]/li[1]/form/div[2]/input').clear()
driver.find_element_by_xpath('/html/body/div[1]/div/section/div[2]/ul[2]/li[1]/form/div[2]/input').send_keys('117243')
driver.find_element_by_xpath('/html/body/div[1]/div/section/div[2]/ul[2]/li[1]/form/div[2]/input').submit()
#driver.find_element_by_xpath('/html/body/div[1]/div/section/div[2]/ul[2]/li[1]/form/div[4]/input').click()
driver.quit()